# Generated by Django 3.0.6 on 2020-05-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoInfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='author',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
