# Generated by Django 3.0.6 on 2020-05-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoInfo', '0002_auto_20200515_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
