# Generated by Django 3.0.6 on 2020-05-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoInfo', '0003_auto_20200515_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='author',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='title',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
