# Generated by Django 3.0.6 on 2020-05-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoInfo', '0005_auto_20200515_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='author',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
