# Generated by Django 3.0.6 on 2020-05-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoInfo', '0006_auto_20200515_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='url',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='urlToImage',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
    ]
