# Generated by Django 3.0.6 on 2020-05-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoInfo', '0007_auto_20200516_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
