# Generated by Django 3.0.6 on 2020-05-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoInfo', '0008_auto_20200516_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='crypto',
            name='today_num_of_articles',
            field=models.IntegerField(default=0),
        ),
    ]
