# Generated by Django 3.0.6 on 2020-05-16 09:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoInfo', '0009_crypto_today_num_of_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='crypto',
            name='today_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
