# Generated by Django 3.0.6 on 2020-05-16 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoInfo', '0010_crypto_today_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crypto',
            name='today_date',
        ),
        migrations.RemoveField(
            model_name='crypto',
            name='today_num_of_articles',
        ),
    ]
