# Generated by Django 3.0.6 on 2020-05-16 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoInfo', '0012_crypto_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crypto',
            name='created_at',
        ),
    ]
